services:
  - type: web
    name: Suhail-Md-V1-Down
    env: node
    branch: main
    repo: https://github.com/SuhailTechInfo/Suhail-Md-V1-Down
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_NAME
        sync: ğ›¥ğ¿ğ›¯ğ›¸ ğ›²ğ›ªğ›«ğ‘ˆ ğ›­ğ·
      - key: DATABASE_URL
        sync: false
      - key: HANDLERS
        sync: false
      - key: MODE
        sync: false
      - key: OWNER_NAME
        sunc: ğ›¥ğ¿ğ›¯ğ›¸ ğ›²ğ›ªğ›«ğ‘ˆ
      - key: OWNER_NUMBER
        sync: false
      - key: PACK_AUTHER
        sync: ğ“†©â€âœ˜Ã€ğ–‘Ã¨ğ– ğ•»Ã¬ğ–Ã¹âœ˜ğ“†ª
      - key: SESSION_ID
       synce: false
      - key: SUDO
       synce: false
      - key: WARN_COUNT
       synce: false
      - key: WELCOME
       synce: false
       
